typography_spectrum: 0.9526889086700976
color:
  brandColors:
    - '#44d9e5'
    - '#000000'
    - '#ffffff'
    - '#333333'
    - '#838383'
  brandStrength: 0.75
  lightness: 0.7337201365735382
  saturation: 0.75
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7388222524896264
analytics:
  google: null
  facebook: null
  twitter: null
name: Notable Doodads
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: why
    id: bdecc962-7e25-4652-816b-97b20e15aa60
    type: content
  - name: GC
    url: 'http://guitarcreativity.musicteachershelper.com/'
    type: external
  - name: why
    id: 4d6007a3-57e9-4a49-a119-b749c81269ef
    type: content
favicon: null
title: Notable Doodads
description: don't doo ordinary
purpose: []
