typography_spectrum: 0.9526889086700976
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.75
  lightness: 0.7337201365735382
  saturation: 0.75
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7388222524896264
analytics:
  google: null
  facebook: null
  twitter: null
name: Notable Doodads
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Purpose
    id: bdecc962-7e25-4652-816b-97b20e15aa60
    type: content
  - name: GC
    url: 'http://guitarcreativity.musicteachershelper.com/'
    type: external
favicon: null
title: 'Cool, useful stuff.'
description: don't doo ordinary
purpose: []
